"""Add favorites column

Revision ID: 935842af8c56
Revises: 
Create Date: 2018-12-25 22:46:09.500659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '935842af8c56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('favorite', sa.Boolean(), nullable=True))
    op.alter_column('posts', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('posts', 'favorite')
    # ### end Alembic commands ###
